Add functionality to get fresh state on new connection
canlasla/focall pull request #21
Opened 2023-03-05 20:44 UTC by canlasla

PR implements how the server handles communication between a new client and an already connected client. The idea is to get the state from the already connected client and send it to the new client to process. Here are the steps:

When the client first starts up, call the `ReceiveFreshState` hub on the server. This will select a client to send a state to the new client.

The server will invoke `SendMessageToNewConnection` on the selected client. This will make the selected client grab its current state and call the `SendServerCurrentState` hub on the server. 

The server will receive this state and invoke `ReceiveEncodedMessage` on the new client for it to process.

2023-03-05 20:47 UTC, canlasla commented
[link to pr on connectionserver repo](https://github.com/fontan10/ConnectionServer/pull/1 ) @fontan10 @ayshon

2023-03-06 02:22 UTC, ayshon approved these changes
Looks good sir

2023-03-06 18:19 UTC, fontan10 requested changes

2023-03-06 18:19 UTC, fontan10 commented on MergeSharpWebAPI/ServerConnection/Globals.cs
> +    private const string PropagationMessageServer = "https://localhost:7106/hubs/propagationmessage";
this change should not be merged to master

2023-03-06 18:20 UTC, fontan10 commented on MergeSharpWebAPI/Program.cs
> +            // //Declare TPTPMsg
if youre able to decide on a block to comment out, you can factor it into a function. then just comment out the funciton call

2023-03-06 20:32 UTC, fontan10 commented on MergeSharpWebAPI/Program.cs
> +            Console.WriteLine(JsonConvert.SerializeObject(myLWWSetService.Get(1)));
can you add a TODO: here to change it to the GraphService later

2023-03-06 21:17 UTC, fontan10 approved these changes
good to merge

2023-03-06 21:21 UTC, merged